### ISSUE TITLE
How to download Tiyo manually?

### ISSUE THREAD

**Issue by Lockszmith-GH** [xgi/tiyo#18]
Houdoku is failing to install tiyo plugin.

How can I test the download manually to troubleshoot the issue?

**Comment by dxbh0517** [comment]
Ran into the same issue a few days ago, if you clone the repo then you can build it using `pnpm exec nx run core:build` . the build will create new folder if you copy those to the AppData/Roaming/Houdoku/plugins/@tiyo/core it will work. you might need to run `pnpm install` before building the repo and inside the Houdoku folder after you copy the build depending on what dependencies you already have installed.

**Comment by Lockszmith-GH** [comment]
ok, was wishing a binary will be lurking online somewhere - after all, the plugin update is supposed to be pulling this from somewhere online.

**Comment by xgi** [comment]
This should be resolved with Houdoku 2.15.0. Thanks!
